export interface Bot {
    name: string;
    description: string;
    category: string;
    rating: number;
}

export const bots: Bot[] = [
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
    {
        name: "Meal Planner Bot",
        description: "Plan your weekly meals with personalized recipes.",
        category: "FOOD",
        rating: 2,
    },
    {
        name: "Study Buddy Bot",
        description: "Get help with homework and study schedules.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Fitness Tracker Bot",
        description: "Track your workouts and set fitness goals.",
        category: "HEALTH",
        rating: 3,
    },
    {
        name: "Travel Itinerary Bot",
        description: "Create detailed travel plans and book tickets.",
        category: "TRAVEL",
        rating: 4.8,
    },
    {
        name: "Budget Manager Bot",
        description: "Manage your finances and track expenses.",
        category: "FINANCE",
        rating: 4.2,
    },
    {
        name: "Recipe Finder Bot",
        description: "Find recipes based on ingredients you have.",
        category: "FOOD",
        rating: 3.8,
    },
    {
        name: "Language Learning Bot",
        description: "Practice new languages with interactive lessons.",
        category: "EDUCATION",
        rating: 4,
    },
    {
        name: "Mental Wellness Bot",
        description: "Guided meditation and stress management tips.",
        category: "HEALTH",
        rating: 4.9,
    },
    {
        name: "Event Planner Bot",
        description: "Organize events and send invitations easily.",
        category: "PRODUCTIVITY",
        rating: 3.0,
    },
    {
        name: "Job Search Bot",
        description: "Find job listings and prepare for interviews.",
        category: "CAREER",
        rating: 3.9,
    },
];